# Generated by Django 5.0.7 on 2024-07-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0002_remove_school_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
