# Generated by Django 5.0.7 on 2024-07-14 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0003_school_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='adress',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
