# Generated by Django 5.0.7 on 2024-07-14 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0004_school_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='type',
            new_name='school_group',
        ),
    ]
