# Generated by Django 5.0.7 on 2024-07-14 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0005_rename_type_school_school_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='adress',
            new_name='address',
        ),
    ]
